# Generated by Django 4.2.4 on 2023-08-31 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='title',
        ),
    ]
