# Generated by Django 4.2.4 on 2023-09-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_reply_registration_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='registration_code',
        ),
    ]
